/*!
 * \file opengl_ext.h
 * \date 2015/12/17 13:22
 *
 * \author Alin Stroe
 *
 * \brief extensions support for the OpenGL library
 *
 * \note original version's date 2015/03/30
 * \version 2.0 
*/

#ifndef __OPENGL_EXT_H__
#define __OPENGL_EXT_H__

#ifdef _WIN32
#include <Windows.h>
#endif

#include <gl/GL.h>

#ifdef GL_GLEXT_VERSION
#undef GL_GLEXT_VERSION
#endif // GL_GLEXT_VERSION

#include "glext.h"

#pragma pack (push, 1)

#define API

//! Macro to get the function pointer
/*!      
    \param func_type - the function type
    \param funct_name - the function name

*/
#define GET_FUNCTION_POINTER(func_type, func_name)\
    inline func_type API func_name##_(){\
        static func_type funny = (func_type)wglGetProcAddress(#func_name);\
        return funny;\
    }


#pragma region GL_VERSION_1_3
GET_FUNCTION_POINTER(PFNGLACTIVETEXTUREPROC             , glActiveTexture           )
GET_FUNCTION_POINTER(PFNGLSAMPLECOVERAGEPROC            , glSampleCoverage          )
GET_FUNCTION_POINTER(PFNGLCOMPRESSEDTEXIMAGE3DPROC      , glCompressedTexImage3D    )
GET_FUNCTION_POINTER(PFNGLCOMPRESSEDTEXIMAGE2DPROC      , glCompressedTexImage2D    )
GET_FUNCTION_POINTER(PFNGLCOMPRESSEDTEXIMAGE1DPROC      , glCompressedTexImage1D    )
GET_FUNCTION_POINTER(PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC   , glCompressedTexSubImage3D )
GET_FUNCTION_POINTER(PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC   , glCompressedTexSubImage2D )
GET_FUNCTION_POINTER(PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC   , glCompressedTexSubImage1D )
GET_FUNCTION_POINTER(PFNGLGETCOMPRESSEDTEXIMAGEPROC     , glGetCompressedTexImage   )
GET_FUNCTION_POINTER(PFNGLCLIENTACTIVETEXTUREPROC       , glClientActiveTexture     )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD1DPROC           , glMultiTexCoord1d         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD1DVPROC          , glMultiTexCoord1dv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD1FPROC           , glMultiTexCoord1f         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD1FVPROC          , glMultiTexCoord1fv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD1IPROC           , glMultiTexCoord1i         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD1IVPROC          , glMultiTexCoord1iv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD1SPROC           , glMultiTexCoord1s         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD1SVPROC          , glMultiTexCoord1sv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD2DPROC           , glMultiTexCoord2d         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD2DVPROC          , glMultiTexCoord2dv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD2FPROC           , glMultiTexCoord2f         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD2FVPROC          , glMultiTexCoord2fv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD2IPROC           , glMultiTexCoord2i         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD2IVPROC          , glMultiTexCoord2iv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD2SPROC           , glMultiTexCoord2s         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD2SVPROC          , glMultiTexCoord2sv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD3DPROC           , glMultiTexCoord3d         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD3DVPROC          , glMultiTexCoord3dv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD3FPROC           , glMultiTexCoord3f         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD3FVPROC          , glMultiTexCoord3fv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD3IPROC           , glMultiTexCoord3i         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD3IVPROC          , glMultiTexCoord3iv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD3SPROC           , glMultiTexCoord3s         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD3SVPROC          , glMultiTexCoord3sv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD4DPROC           , glMultiTexCoord4d         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD4DVPROC          , glMultiTexCoord4dv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD4FPROC           , glMultiTexCoord4f         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD4FVPROC          , glMultiTexCoord4fv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD4IPROC           , glMultiTexCoord4i         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD4IVPROC          , glMultiTexCoord4iv        )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD4SPROC           , glMultiTexCoord4s         )
GET_FUNCTION_POINTER(PFNGLMULTITEXCOORD4SVPROC          , glMultiTexCoord4sv        )
GET_FUNCTION_POINTER(PFNGLLOADTRANSPOSEMATRIXFPROC      , glLoadTransposeMatrixf    )
GET_FUNCTION_POINTER(PFNGLLOADTRANSPOSEMATRIXDPROC      , glLoadTransposeMatrixd    )
GET_FUNCTION_POINTER(PFNGLMULTTRANSPOSEMATRIXFPROC      , glMultTransposeMatrixf    )
GET_FUNCTION_POINTER(PFNGLMULTTRANSPOSEMATRIXDPROC      , glMultTransposeMatrixd    )

#define glActiveTexture           glActiveTexture_()           
#define glSampleCoverage          glSampleCoverage_()          
#define glCompressedTexImage3D    glCompressedTexImage3D_()    
#define glCompressedTexImage2D    glCompressedTexImage2D_()    
#define glCompressedTexImage1D    glCompressedTexImage1D_()    
#define glCompressedTexSubImage3D glCompressedTexSubImage3D_() 
#define glCompressedTexSubImage2D glCompressedTexSubImage2D_() 
#define glCompressedTexSubImage1D glCompressedTexSubImage1D_() 
#define glGetCompressedTexImage   glGetCompressedTexImage_()   
#define glClientActiveTexture     glClientActiveTexture_()     
#define glMultiTexCoord1d         glMultiTexCoord1d_()         
#define glMultiTexCoord1dv        glMultiTexCoord1dv_()        
#define glMultiTexCoord1f         glMultiTexCoord1f_()         
#define glMultiTexCoord1fv        glMultiTexCoord1fv_()        
#define glMultiTexCoord1i         glMultiTexCoord1i_()         
#define glMultiTexCoord1iv        glMultiTexCoord1iv_()        
#define glMultiTexCoord1s         glMultiTexCoord1s_()         
#define glMultiTexCoord1sv        glMultiTexCoord1sv_()        
#define glMultiTexCoord2d         glMultiTexCoord2d_()         
#define glMultiTexCoord2dv        glMultiTexCoord2dv_()        
#define glMultiTexCoord2f         glMultiTexCoord2f_()         
#define glMultiTexCoord2fv        glMultiTexCoord2fv_()        
#define glMultiTexCoord2i         glMultiTexCoord2i_()         
#define glMultiTexCoord2iv        glMultiTexCoord2iv_()        
#define glMultiTexCoord2s         glMultiTexCoord2s_()         
#define glMultiTexCoord2sv        glMultiTexCoord2sv_()        
#define glMultiTexCoord3d         glMultiTexCoord3d_()         
#define glMultiTexCoord3dv        glMultiTexCoord3dv_()        
#define glMultiTexCoord3f         glMultiTexCoord3f_()         
#define glMultiTexCoord3fv        glMultiTexCoord3fv_()        
#define glMultiTexCoord3i         glMultiTexCoord3i_()         
#define glMultiTexCoord3iv        glMultiTexCoord3iv_()        
#define glMultiTexCoord3s         glMultiTexCoord3s_()         
#define glMultiTexCoord3sv        glMultiTexCoord3sv_()        
#define glMultiTexCoord4d         glMultiTexCoord4d_()         
#define glMultiTexCoord4dv        glMultiTexCoord4dv_()        
#define glMultiTexCoord4f         glMultiTexCoord4f_()         
#define glMultiTexCoord4fv        glMultiTexCoord4fv_()        
#define glMultiTexCoord4i         glMultiTexCoord4i_()         
#define glMultiTexCoord4iv        glMultiTexCoord4iv_()        
#define glMultiTexCoord4s         glMultiTexCoord4s_()         
#define glMultiTexCoord4sv        glMultiTexCoord4sv_()        
#define glLoadTransposeMatrixf    glLoadTransposeMatrixf_()    
#define glLoadTransposeMatrixd    glLoadTransposeMatrixd_()    
#define glMultTransposeMatrixf    glMultTransposeMatrixf_()    
#define glMultTransposeMatrixd    glMultTransposeMatrixd_()    

#pragma endregion

#pragma region GL_VERSION_1_5

GET_FUNCTION_POINTER(PFNGLGENQUERIESPROC,           glGenQueries               )
GET_FUNCTION_POINTER(PFNGLDELETEQUERIESPROC,        glDeleteQueries            )
GET_FUNCTION_POINTER(PFNGLISQUERYPROC,              glIsQuery                  )
GET_FUNCTION_POINTER(PFNGLBEGINQUERYPROC,           glBeginQuery               )
GET_FUNCTION_POINTER(PFNGLENDQUERYPROC,             glEndQuery                 )
GET_FUNCTION_POINTER(PFNGLGETQUERYIVPROC,           glGetQueryiv               )
GET_FUNCTION_POINTER(PFNGLGETQUERYOBJECTIVPROC,     glGetQueryObjectiv         )
GET_FUNCTION_POINTER(PFNGLGETQUERYOBJECTUIVPROC,    glGetQueryObjectuiv        )
GET_FUNCTION_POINTER(PFNGLBINDBUFFERPROC,           glBindBuffer               )
GET_FUNCTION_POINTER(PFNGLDELETEBUFFERSPROC,        glDeleteBuffers            )
GET_FUNCTION_POINTER(PFNGLGENBUFFERSPROC,           glGenBuffers               )
GET_FUNCTION_POINTER(PFNGLISBUFFERPROC,             glIsBuffer                 )
GET_FUNCTION_POINTER(PFNGLBUFFERDATAPROC,           glBufferData               )
GET_FUNCTION_POINTER(PFNGLBUFFERSUBDATAPROC,        glBufferSubData            )
GET_FUNCTION_POINTER(PFNGLGETBUFFERSUBDATAPROC,     glGetBufferSubData         )
GET_FUNCTION_POINTER(PFNGLMAPBUFFERPROC,            glMapBuffer                )
GET_FUNCTION_POINTER(PFNGLUNMAPBUFFERPROC,          glUnmapBuffer              )
GET_FUNCTION_POINTER(PFNGLGETBUFFERPARAMETERIVPROC, glGetBufferParameteriv     )
GET_FUNCTION_POINTER(PFNGLGETBUFFERPOINTERVPROC,    glGetBufferPointerv        )

#define glGenQueries            glGenQueries_()
#define glDeleteQueries         glDeleteQueries_()        
#define glIsQuery               glIsQuery_()             
#define glBeginQuery            glBeginQuery_()          
#define glEndQuery              glEndQuery_()            
#define glGetQueryiv            glGetQueryiv_()          
#define glGetQueryObjectiv      glGetQueryObjectiv_()    
#define glGetQueryObjectuiv     glGetQueryObjectuiv_()   
#define glBindBuffer            glBindBuffer_()          
#define glDeleteBuffers         glDeleteBuffers_()       
#define glGenBuffers            glGenBuffers_()          
#define glIsBuffer              glIsBuffer_()            
#define glBufferData            glBufferData_()          
#define glBufferSubData         glBufferSubData_()       
#define glGetBufferSubData      glGetBufferSubData_()    
#define glMapBuffer             glMapBuffer_()           
#define glUnmapBuffer           glUnmapBuffer_()        
#define glGetBufferParameteriv  glGetBufferParameteriv_()
#define glGetBufferPointerv     glGetBufferPointerv_()   

#pragma endregion

#pragma region GL_VERSION_2_0
GET_FUNCTION_POINTER(PFNGLBLENDEQUATIONSEPARATEPROC         , glBlendEquationSeparate       )
GET_FUNCTION_POINTER(PFNGLDRAWBUFFERSPROC                   , glDrawBuffers                 )
GET_FUNCTION_POINTER(PFNGLSTENCILOPSEPARATEPROC             , glStencilOpSeparate           )
GET_FUNCTION_POINTER(PFNGLSTENCILFUNCSEPARATEPROC           , glStencilFuncSeparate         )
GET_FUNCTION_POINTER(PFNGLSTENCILMASKSEPARATEPROC           , glStencilMaskSeparate         )
GET_FUNCTION_POINTER(PFNGLATTACHSHADERPROC                  , glAttachShader                )
GET_FUNCTION_POINTER(PFNGLBINDATTRIBLOCATIONPROC            , glBindAttribLocation          )
GET_FUNCTION_POINTER(PFNGLCOMPILESHADERPROC                 , glCompileShader               )
GET_FUNCTION_POINTER(PFNGLCREATEPROGRAMPROC                 , glCreateProgram               )
GET_FUNCTION_POINTER(PFNGLCREATESHADERPROC                  , glCreateShader                )
GET_FUNCTION_POINTER(PFNGLDELETEPROGRAMPROC                 , glDeleteProgram               )
GET_FUNCTION_POINTER(PFNGLDELETESHADERPROC                  , glDeleteShader                )
GET_FUNCTION_POINTER(PFNGLDETACHSHADERPROC                  , glDetachShader                )
GET_FUNCTION_POINTER(PFNGLDISABLEVERTEXATTRIBARRAYPROC      , glDisableVertexAttribArray    )
GET_FUNCTION_POINTER(PFNGLENABLEVERTEXATTRIBARRAYPROC       , glEnableVertexAttribArray     )
GET_FUNCTION_POINTER(PFNGLGETACTIVEATTRIBPROC               , glGetActiveAttrib             )
GET_FUNCTION_POINTER(PFNGLGETACTIVEUNIFORMPROC              , glGetActiveUniform            )
GET_FUNCTION_POINTER(PFNGLGETATTACHEDSHADERSPROC            , glGetAttachedShaders          )
GET_FUNCTION_POINTER(PFNGLGETATTRIBLOCATIONPROC             , glGetAttribLocation           )
GET_FUNCTION_POINTER(PFNGLGETPROGRAMIVPROC                  , glGetProgramiv                )
GET_FUNCTION_POINTER(PFNGLGETPROGRAMINFOLOGPROC             , glGetProgramInfoLog           )
GET_FUNCTION_POINTER(PFNGLGETSHADERIVPROC                   , glGetShaderiv                 )
GET_FUNCTION_POINTER(PFNGLGETSHADERINFOLOGPROC              , glGetShaderInfoLog            )
GET_FUNCTION_POINTER(PFNGLGETSHADERSOURCEPROC               , glGetShaderSource             )
GET_FUNCTION_POINTER(PFNGLGETUNIFORMLOCATIONPROC            , glGetUniformLocation          )
GET_FUNCTION_POINTER(PFNGLGETUNIFORMFVPROC                  , glGetUniformfv                )
GET_FUNCTION_POINTER(PFNGLGETUNIFORMIVPROC                  , glGetUniformiv                )
GET_FUNCTION_POINTER(PFNGLGETVERTEXATTRIBDVPROC             , glGetVertexAttribdv           )
GET_FUNCTION_POINTER(PFNGLGETVERTEXATTRIBFVPROC             , glGetVertexAttribfv           )
GET_FUNCTION_POINTER(PFNGLGETVERTEXATTRIBIVPROC             , glGetVertexAttribiv           )
GET_FUNCTION_POINTER(PFNGLGETVERTEXATTRIBPOINTERVPROC       , glGetVertexAttribPointer      )
GET_FUNCTION_POINTER(PFNGLISPROGRAMPROC                     , glIsProgram                   )
GET_FUNCTION_POINTER(PFNGLISSHADERPROC                      , glIsShader                    )
GET_FUNCTION_POINTER(PFNGLLINKPROGRAMPROC                   , glLinkProgram                 )
GET_FUNCTION_POINTER(PFNGLSHADERSOURCEPROC                  , glShaderSource                )
GET_FUNCTION_POINTER(PFNGLUSEPROGRAMPROC                    , glUseProgram                  )
GET_FUNCTION_POINTER(PFNGLUNIFORM1FPROC                     , glUniform1f                   )
GET_FUNCTION_POINTER(PFNGLUNIFORM2FPROC                     , glUniform2f                   )
GET_FUNCTION_POINTER(PFNGLUNIFORM3FPROC                     , glUniform3f                   )
GET_FUNCTION_POINTER(PFNGLUNIFORM4FPROC                     , glUniform4f                   )
GET_FUNCTION_POINTER(PFNGLUNIFORM1IPROC                     , glUniform1i                   )
GET_FUNCTION_POINTER(PFNGLUNIFORM2IPROC                     , glUniform2i                   )
GET_FUNCTION_POINTER(PFNGLUNIFORM3IPROC                     , glUniform3i                   )
GET_FUNCTION_POINTER(PFNGLUNIFORM4IPROC                     , glUniform4i                   )
GET_FUNCTION_POINTER(PFNGLUNIFORM1FVPROC                    , glUniform1fv                  )
GET_FUNCTION_POINTER(PFNGLUNIFORM2FVPROC                    , glUniform2fv                  )
GET_FUNCTION_POINTER(PFNGLUNIFORM3FVPROC                    , glUniform3fv                  )
GET_FUNCTION_POINTER(PFNGLUNIFORM4FVPROC                    , glUniform4fv                  )
GET_FUNCTION_POINTER(PFNGLUNIFORM1IVPROC                    , glUniform1iv                  )
GET_FUNCTION_POINTER(PFNGLUNIFORM2IVPROC                    , glUniform2iv                  )
GET_FUNCTION_POINTER(PFNGLUNIFORM3IVPROC                    , glUniform3iv                  )
GET_FUNCTION_POINTER(PFNGLUNIFORM4IVPROC                    , glUniform4iv                  )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX2FVPROC              , glUniformMatrix2fv            )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX3FVPROC              , glUniformMatrix3fv            )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX4FVPROC              , glUniformMatrix4fv            )
GET_FUNCTION_POINTER(PFNGLVALIDATEPROGRAMPROC               , glValidateProgram             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB1DPROC                , glVertexAttrib1d              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB1DVPROC               , glVertexAttrib1dv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB1FPROC                , glVertexAttrib1f              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB1FVPROC               , glVertexAttrib1fv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB1SPROC                , glVertexAttrib1s              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB1SVPROC               , glVertexAttrib1sv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB2DPROC                , glVertexAttrib2d              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB2DVPROC               , glVertexAttrib2dv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB2FPROC                , glVertexAttrib2f              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB2FVPROC               , glVertexAttrib2fv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB2SPROC                , glVertexAttrib2s              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB2SVPROC               , glVertexAttrib2sv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB3DPROC                , glVertexAttrib3d              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB3DVPROC               , glVertexAttrib3dv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB3FPROC                , glVertexAttrib3f              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB3FVPROC               , glVertexAttrib3fv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB3SPROC                , glVertexAttrib3s              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB3SVPROC               , glVertexAttrib3sv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4NBVPROC              , glVertexAttrib4Nbv            )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4NIVPROC              , glVertexAttrib4Niv            )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4NSVPROC              , glVertexAttrib4Nsv            )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4NUBPROC              , glVertexAttrib4Nub            )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4NUBVPROC             , glVertexAttrib4Nubv           )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4NUIVPROC             , glVertexAttrib4Nuiv           )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4NUSVPROC             , glVertexAttrib4Nusv           )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4BVPROC               , glVertexAttrib4bv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4DPROC                , glVertexAttrib4d              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4DVPROC               , glVertexAttrib4dv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4FPROC                , glVertexAttrib4f              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4FVPROC               , glVertexAttrib4fv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4IVPROC               , glVertexAttrib4iv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4SPROC                , glVertexAttrib4s              )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4SVPROC               , glVertexAttrib4sv             )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4UBVPROC              , glVertexAttrib4ubv            )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4UIVPROC              , glVertexAttrib4uiv            )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIB4USVPROC              , glVertexAttrib4usv            )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBPOINTERPROC           , glVertexAttribPointer         )

#define glBlendEquationSeparate         glBlendEquationSeparate_()          
#define glDrawBuffers                   glDrawBuffers_()                 
#define glStencilOpSeparate             glStencilOpSeparate_()           
#define glStencilFuncSeparate           glStencilFuncSeparate_()         
#define glStencilMaskSeparate           glStencilMaskSeparate_()         
#define glAttachShader                  glAttachShader_()                
#define glBindAttribLocation            glBindAttribLocation_()          
#define glCompileShader                 glCompileShader_()               
#define glCreateProgram                 glCreateProgram_()               
#define glCreateShader                  glCreateShader_()                
#define glDeleteProgram                 glDeleteProgram_()               
#define glDeleteShader                  glDeleteShader_()                
#define glDetachShader                  glDetachShader_()                
#define glDisableVertexAttribArray      glDisableVertexAttribArray_()    
#define glEnableVertexAttribArray       glEnableVertexAttribArray_()     
#define glGetActiveAttrib               glGetActiveAttrib_()             
#define glGetActiveUniform              glGetActiveUniform_()            
#define glGetAttachedShaders            glGetAttachedShaders_()          
#define glGetAttribLocation             glGetAttribLocation_()           
#define glGetProgramiv                  glGetProgramiv_()                
#define glGetProgramInfoLog             glGetProgramInfoLog_()           
#define glGetShaderiv                   glGetShaderiv_()                 
#define glGetShaderInfoLog              glGetShaderInfoLog_()            
#define glGetShaderSource               glGetShaderSource_()             
#define glGetUniformLocation            glGetUniformLocation_()          
#define glGetUniformfv                  glGetUniformfv_()                
#define glGetUniformiv                  glGetUniformiv_()                
#define glGetVertexAttribdv             glGetVertexAttribdv_()           
#define glGetVertexAttribfv             glGetVertexAttribfv_()           
#define glGetVertexAttribiv             glGetVertexAttribiv_()           
#define glGetVertexAttribPointer        glGetVertexAttribPointer_()      
#define glIsProgram                     glIsProgram_()                   
#define glIsShader                      glIsShader_()                    
#define glLinkProgram                   glLinkProgram_()                 
#define glShaderSource                  glShaderSource_()                
#define glUseProgram                    glUseProgram_()
#define glUniform1f                     glUniform1f_()                   
#define glUniform2f                     glUniform2f_()                   
#define glUniform3f                     glUniform3f_()                   
#define glUniform4f                     glUniform4f_()                   
#define glUniform1i                     glUniform1i_()                   
#define glUniform2i                     glUniform2i_()                   
#define glUniform3i                     glUniform3i_()                   
#define glUniform4i                     glUniform4i_()                   
#define glUniform1fv                    glUniform1fv_()                  
#define glUniform2fv                    glUniform2fv_()                  
#define glUniform3fv                    glUniform3fv_()                  
#define glUniform4fv                    glUniform4fv_()                  
#define glUniform1iv                    glUniform1iv_()                  
#define glUniform2iv                    glUniform2iv_()                  
#define glUniform3iv                    glUniform3iv_()                  
#define glUniform4iv                    glUniform4iv_()                  
#define glUniformMatrix2fv              glUniformMatrix2fv_()            
#define glUniformMatrix3fv              glUniformMatrix3fv_()            
#define glUniformMatrix4fv              glUniformMatrix4fv_()            
#define glValidateProgram               glValidateProgram_()             
#define glVertexAttrib1d                glVertexAttrib1d_()              
#define glVertexAttrib1dv               glVertexAttrib1dv_()             
#define glVertexAttrib1f                glVertexAttrib1f_()              
#define glVertexAttrib1fv               glVertexAttrib1fv_()             
#define glVertexAttrib1s                glVertexAttrib1s_()              
#define glVertexAttrib1sv               glVertexAttrib1sv_()             
#define glVertexAttrib2d                glVertexAttrib2d_()              
#define glVertexAttrib2dv               glVertexAttrib2dv_()             
#define glVertexAttrib2f                glVertexAttrib2f_()              
#define glVertexAttrib2fv               glVertexAttrib2fv_()             
#define glVertexAttrib2s                glVertexAttrib2s_()              
#define glVertexAttrib2sv               glVertexAttrib2sv_()             
#define glVertexAttrib3d                glVertexAttrib3d_()              
#define glVertexAttrib3dv               glVertexAttrib3dv_()             
#define glVertexAttrib3f                glVertexAttrib3f_()              
#define glVertexAttrib3fv               glVertexAttrib3fv_()             
#define glVertexAttrib3s                glVertexAttrib3s_()              
#define glVertexAttrib3sv               glVertexAttrib3sv_()             
#define glVertexAttrib4Nbv              glVertexAttrib4Nbv_()            
#define glVertexAttrib4Niv              glVertexAttrib4Niv_()            
#define glVertexAttrib4Nsv              glVertexAttrib4Nsv_()            
#define glVertexAttrib4Nub              glVertexAttrib4Nub_()            
#define glVertexAttrib4Nubv             glVertexAttrib4Nubv_()           
#define glVertexAttrib4Nuiv             glVertexAttrib4Nuiv_()           
#define glVertexAttrib4Nusv             glVertexAttrib4Nusv_()           
#define glVertexAttrib4bv               glVertexAttrib4bv_()             
#define glVertexAttrib4d                glVertexAttrib4d_()              
#define glVertexAttrib4dv               glVertexAttrib4dv_()             
#define glVertexAttrib4f                glVertexAttrib4f_()              
#define glVertexAttrib4fv               glVertexAttrib4fv_()             
#define glVertexAttrib4iv               glVertexAttrib4iv_()             
#define glVertexAttrib4s                glVertexAttrib4s_()              
#define glVertexAttrib4sv               glVertexAttrib4sv_()             
#define glVertexAttrib4ubv              glVertexAttrib4ubv_()            
#define glVertexAttrib4uiv              glVertexAttrib4uiv_()            
#define glVertexAttrib4usv              glVertexAttrib4usv_()            
#define glVertexAttribPointer           glVertexAttribPointer_()         
#pragma endregion

#pragma region GL_NV_shader_buffer_load
GET_FUNCTION_POINTER(PFNGLMAKEBUFFERRESIDENTNVPROC           , glMakeBufferResidentNV               )
GET_FUNCTION_POINTER(PFNGLMAKEBUFFERNONRESIDENTNVPROC        , glMakeBufferNonResidentNV            )
GET_FUNCTION_POINTER(PFNGLISBUFFERRESIDENTNVPROC             , glIsBufferResidentNV                 )
GET_FUNCTION_POINTER(PFNGLMAKENAMEDBUFFERRESIDENTNVPROC      , glMakeNamedBufferResidentNV          )
GET_FUNCTION_POINTER(PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC   , glMakeNamedBufferNonResidentNV       )
GET_FUNCTION_POINTER(PFNGLISNAMEDBUFFERRESIDENTNVPROC        , glIsNamedBufferResidentNV            )
GET_FUNCTION_POINTER(PFNGLGETBUFFERPARAMETERUI64VNVPROC      , glGetBufferParameterui64vNV          )
GET_FUNCTION_POINTER(PFNGLGETNAMEDBUFFERPARAMETERUI64VNVPROC , glGetNamedBufferParameterui64vNV     )
GET_FUNCTION_POINTER(PFNGLGETINTEGERUI64VNVPROC              , glGetIntegerui64vNV                  )
GET_FUNCTION_POINTER(PFNGLUNIFORMUI64NVPROC                  , glUniformui64NV                      )
GET_FUNCTION_POINTER(PFNGLUNIFORMUI64VNVPROC                 , glUniformui64vNV                     )
GET_FUNCTION_POINTER(PFNGLGETUNIFORMUI64VNVPROC              , glGetUniformui64vNV                  )
GET_FUNCTION_POINTER(PFNGLPROGRAMUNIFORMUI64NVPROC           , glProgramUniformui64NV               )
GET_FUNCTION_POINTER(PFNGLPROGRAMUNIFORMUI64VNVPROC          , glProgramUniformui64vNV              )


#define glMakeBufferResidentNV              glMakeBufferResidentNV_()           
#define glMakeBufferNonResidentNV           glMakeBufferNonResidentNV_()
#define glIsBufferResidentNV                glIsBufferResidentNV_()             
#define glMakeNamedBufferResidentNV         glMakeNamedBufferResidentNV_()      
#define glMakeNamedBufferNonResidentNV      glMakeNamedBufferNonResidentNV_()   
#define glIsNamedBufferResidentNV           glIsNamedBufferResidentNV_()        
#define glGetBufferParameterui64vNV         glGetBufferParameterui64vNV_()      
#define glGetNamedBufferParameterui64vNV    glGetNamedBufferParameterui64vNV_() 
#define glGetIntegerui64vNV                 glGetIntegerui64vNV_()              
#define glUniformui64NV                     glUniformui64NV_()                  
#define glUniformui64vNV                    glUniformui64vNV_()                 
#define glGetUniformui64vNV                 glGetUniformui64vNV_()              
#define glProgramUniformui64NV              glProgramUniformui64NV_()           
#define glProgramUniformui64vNV             glProgramUniformui64vNV_()          
#pragma endregion

#pragma region GL_ARB_instanced_arrays
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBDIVISORARBPROC, glVertexAttribDivisorARB)
#define glVertexAttribDivisorARB glVertexAttribDivisorARB_()
#pragma endregion

#pragma region GL_NV_vertex_buffer_unified_memory   
GET_FUNCTION_POINTER(PFNGLBUFFERADDRESSRANGENVPROC      , glBufferAddressRangeNV    )
GET_FUNCTION_POINTER(PFNGLVERTEXFORMATNVPROC            , glVertexFormatNV          )
GET_FUNCTION_POINTER(PFNGLNORMALFORMATNVPROC            , glNormalFormatNV          )
GET_FUNCTION_POINTER(PFNGLCOLORFORMATNVPROC             , glColorFormatNV           )
GET_FUNCTION_POINTER(PFNGLINDEXFORMATNVPROC             , glIndexFormatNV           )
GET_FUNCTION_POINTER(PFNGLTEXCOORDFORMATNVPROC          , glTexCoordFormatNV        )
GET_FUNCTION_POINTER(PFNGLEDGEFLAGFORMATNVPROC          , glEdgeFlagFormatNV        )
GET_FUNCTION_POINTER(PFNGLSECONDARYCOLORFORMATNVPROC    , glSecondaryColorFormatNV  )
GET_FUNCTION_POINTER(PFNGLFOGCOORDFORMATNVPROC          , glFogCoordFormatNV        )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBFORMATNVPROC      , glVertexAttribFormatNV    )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBIFORMATNVPROC     , glVertexAttribIFormatNV   )
GET_FUNCTION_POINTER(PFNGLGETINTEGERUI64I_VNVPROC       , glGetIntegerui64i_vNV     )

#define glBufferAddressRangeNV      glBufferAddressRangeNV_()  
#define glVertexFormatNV            glVertexFormatNV_()        
#define glNormalFormatNV            glNormalFormatNV_()        
#define glColorFormatNV             glColorFormatNV_()         
#define glIndexFormatNV             glIndexFormatNV_()         
#define glTexCoordFormatNV          glTexCoordFormatNV_()      
#define glEdgeFlagFormatNV          glEdgeFlagFormatNV_()      
#define glSecondaryColorFormatNV    glSecondaryColorFormatNV_()
#define glFogCoordFormatNV          glFogCoordFormatNV_()      
#define glVertexAttribFormatNV      glVertexAttribFormatNV_()  
#define glVertexAttribIFormatNV     glVertexAttribIFormatNV_() 
#define glGetIntegerui64i_vNV       glGetIntegerui64i_vNV_()   
#pragma endregion

#pragma region(GL_EXT_framebuffer_object)

GET_FUNCTION_POINTER(PFNGLISRENDERBUFFEREXTPROC                         , glIsRenderbufferEXT                       )
GET_FUNCTION_POINTER(PFNGLBINDRENDERBUFFEREXTPROC                       , glBindRenderbufferEXT                     )
GET_FUNCTION_POINTER(PFNGLDELETERENDERBUFFERSEXTPROC                    , glDeleteRenderbuffersEXT                  )
GET_FUNCTION_POINTER(PFNGLGENRENDERBUFFERSEXTPROC                       , glGenRenderbuffersEXT                     )
GET_FUNCTION_POINTER(PFNGLRENDERBUFFERSTORAGEEXTPROC                    , glRenderbufferStorageEXT                  )
GET_FUNCTION_POINTER(PFNGLGETRENDERBUFFERPARAMETERIVEXTPROC             , glGetRenderbufferParameterivEXT           )
GET_FUNCTION_POINTER(PFNGLISFRAMEBUFFEREXTPROC                          , glIsFramebufferEXT                        )
GET_FUNCTION_POINTER(PFNGLBINDFRAMEBUFFEREXTPROC                        , glBindFramebufferEXT                      )
GET_FUNCTION_POINTER(PFNGLDELETEFRAMEBUFFERSEXTPROC                     , glDeleteFramebuffersEXT                   )
GET_FUNCTION_POINTER(PFNGLGENFRAMEBUFFERSEXTPROC                        , glGenFramebuffersEXT                      )
GET_FUNCTION_POINTER(PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC                 , glCheckFramebufferStatusEXT               )
GET_FUNCTION_POINTER(PFNGLFRAMEBUFFERTEXTURE1DEXTPROC                   , glFramebufferTexture1DEXT                 )
GET_FUNCTION_POINTER(PFNGLFRAMEBUFFERTEXTURE2DEXTPROC                   , glFramebufferTexture2DEXT                 )
GET_FUNCTION_POINTER(PFNGLFRAMEBUFFERTEXTURE3DEXTPROC                   , glFramebufferTexture3DEXT                 )
GET_FUNCTION_POINTER(PFNGLFRAMEBUFFERRENDERBUFFEREXTPROC                , glFramebufferRenderbufferEXT              )
GET_FUNCTION_POINTER(PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVEXTPROC    , glGetFramebufferAttachmentParameterivEXT  )
GET_FUNCTION_POINTER(PFNGLGENERATEMIPMAPEXTPROC                         , glGenerateMipmapEXT                       )

#define glIsRenderbufferEXT                       glIsRenderbufferEXT_()                       
#define glBindRenderbufferEXT                     glBindRenderbufferEXT_()
#define glDeleteRenderbuffersEXT                  glDeleteRenderbuffersEXT_()
#define glGenRenderbuffersEXT                     glGenRenderbuffersEXT_()
#define glRenderbufferStorageEXT                  glRenderbufferStorageEXT_()
#define glGetRenderbufferParameterivEXT           glGetRenderbufferParameterivEXT_()
#define glIsFramebufferEXT                        glIsFramebufferEXT_()
#define glBindFramebufferEXT                      glBindFramebufferEXT_()
#define glDeleteFramebuffersEXT                   glDeleteFramebuffersEXT_()
#define glGenFramebuffersEXT                      glGenFramebuffersEXT_()
#define glCheckFramebufferStatusEXT               glCheckFramebufferStatusEXT_()
#define glFramebufferTexture1DEXT                 glFramebufferTexture1DEXT_()
#define glFramebufferTexture2DEXT                 glFramebufferTexture2DEXT_()
#define glFramebufferTexture3DEXT                 glFramebufferTexture3DEXT_()
#define glFramebufferRenderbufferEXT              glFramebufferRenderbufferEXT_()
#define glGetFramebufferAttachmentParameterivEXT  glGetFramebufferAttachmentParameterivEXT_()
#define glGenerateMipmapEXT                       glGenerateMipmapEXT_()

#pragma endregion

#pragma region (GL_EXT_framebuffer_multisample)
GET_FUNCTION_POINTER(PFNGLRENDERBUFFERSTORAGEMULTISAMPLEEXTPROC, glRenderbufferStorageMultisampleEXT)
#define glRenderbufferStorageMultisampleEXT glRenderbufferStorageMultisampleEXT_()
#pragma endregion

#pragma region(GL_EXT_framebuffer_blit)
GET_FUNCTION_POINTER(PFNGLBLITFRAMEBUFFEREXTPROC, glBlitFramebufferEXT)
#define glBlitFramebufferEXT glBlitFramebufferEXT_()
#pragma endregion

#pragma region(GL_ARB_vertex_shader)
GET_FUNCTION_POINTER(PFNGLBINDATTRIBLOCATIONARBPROC,    glBindAttribLocationARB )
GET_FUNCTION_POINTER(PFNGLGETACTIVEATTRIBARBPROC,       glGetActiveAttribARB    )
GET_FUNCTION_POINTER(PFNGLGETATTRIBLOCATIONARBPROC,     glGetAttribLocationARB  )

#define glBindAttribLocationARB glBindAttribLocationARB_()
#define glGetActiveAttribARB    glGetActiveAttribARB_()   
#define glGetAttribLocationARB  glGetAttribLocationARB_() 
#pragma endregion

#pragma region(GL_ARB_fragment_shader)
GET_FUNCTION_POINTER(PFNGLDELETEOBJECTARBPROC,          glDeleteObjectARB        )
GET_FUNCTION_POINTER(PFNGLGETHANDLEARBPROC,             glGetHandleARB           )
GET_FUNCTION_POINTER(PFNGLDETACHOBJECTARBPROC,          glDetachObjectARB        )
GET_FUNCTION_POINTER(PFNGLCREATESHADEROBJECTARBPROC,    glCreateShaderObjectARB  )
GET_FUNCTION_POINTER(PFNGLSHADERSOURCEARBPROC,          glShaderSourceARB        )
GET_FUNCTION_POINTER(PFNGLCOMPILESHADERARBPROC,         glCompileShaderARB       )
GET_FUNCTION_POINTER(PFNGLCREATEPROGRAMOBJECTARBPROC,   glCreateProgramObjectARB )
GET_FUNCTION_POINTER(PFNGLATTACHOBJECTARBPROC,          glAttachObjectARB        )
GET_FUNCTION_POINTER(PFNGLLINKPROGRAMARBPROC,           glLinkProgramARB         )
GET_FUNCTION_POINTER(PFNGLUSEPROGRAMOBJECTARBPROC,      glUseProgramObjectARB    )
GET_FUNCTION_POINTER(PFNGLVALIDATEPROGRAMARBPROC,       glValidateProgramARB     )
GET_FUNCTION_POINTER(PFNGLUNIFORM1FARBPROC,             glUniform1fARB           )
GET_FUNCTION_POINTER(PFNGLUNIFORM2FARBPROC,             glUniform2fARB           )
GET_FUNCTION_POINTER(PFNGLUNIFORM3FARBPROC,             glUniform3fARB           )
GET_FUNCTION_POINTER(PFNGLUNIFORM4FARBPROC,             glUniform4fARB           )
GET_FUNCTION_POINTER(PFNGLUNIFORM1IARBPROC,             glUniform1iARB           )
GET_FUNCTION_POINTER(PFNGLUNIFORM2IARBPROC,             glUniform2iARB           )
GET_FUNCTION_POINTER(PFNGLUNIFORM3IARBPROC,             glUniform3iARB           )
GET_FUNCTION_POINTER(PFNGLUNIFORM4IARBPROC,             glUniform4iARB           )
GET_FUNCTION_POINTER(PFNGLUNIFORM1FVARBPROC,            glUniform1fvARB          )
GET_FUNCTION_POINTER(PFNGLUNIFORM2FVARBPROC,            glUniform2fvARB          )
GET_FUNCTION_POINTER(PFNGLUNIFORM3FVARBPROC,            glUniform3fvARB          )
GET_FUNCTION_POINTER(PFNGLUNIFORM4FVARBPROC,            glUniform4fvARB          )
GET_FUNCTION_POINTER(PFNGLUNIFORM1IVARBPROC,            glUniform1ivARB          )
GET_FUNCTION_POINTER(PFNGLUNIFORM2IVARBPROC,            glUniform2ivARB          )
GET_FUNCTION_POINTER(PFNGLUNIFORM3IVARBPROC,            glUniform3ivARB          )
GET_FUNCTION_POINTER(PFNGLUNIFORM4IVARBPROC,            glUniform4ivARB          )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX2FVARBPROC,      glUniformMatrix2fvARB    )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX3FVARBPROC,      glUniformMatrix3fvARB    )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX4FVARBPROC,      glUniformMatrix4fvARB    )
GET_FUNCTION_POINTER(PFNGLGETOBJECTPARAMETERFVARBPROC,  glGetObjectParameterfvARB)
GET_FUNCTION_POINTER(PFNGLGETOBJECTPARAMETERIVARBPROC,  glGetObjectParameterivARB)
GET_FUNCTION_POINTER(PFNGLGETINFOLOGARBPROC,            glGetInfoLogARB          )
GET_FUNCTION_POINTER(PFNGLGETATTACHEDOBJECTSARBPROC,    glGetAttachedObjectsARB  )
GET_FUNCTION_POINTER(PFNGLGETUNIFORMLOCATIONARBPROC,    glGetUniformLocationARB  )
GET_FUNCTION_POINTER(PFNGLGETACTIVEUNIFORMARBPROC,      glGetActiveUniformARB    )
GET_FUNCTION_POINTER(PFNGLGETUNIFORMFVARBPROC,          glGetUniformfvARB        )
GET_FUNCTION_POINTER(PFNGLGETUNIFORMIVARBPROC,          glGetUniformivARB        )
GET_FUNCTION_POINTER(PFNGLGETSHADERSOURCEARBPROC,       glGetShaderSourceARB     )

#define glDeleteObjectARB          glDeleteObjectARB_()
#define glGetHandleARB             glGetHandleARB_()
#define glDetachObjectARB          glDetachObjectARB_()
#define glCreateShaderObjectARB    glCreateShaderObjectARB_()
#define glShaderSourceARB          glShaderSourceARB_()
#define glCompileShaderARB         glCompileShaderARB_()
#define glCreateProgramObjectARB   glCreateProgramObjectARB_()
#define glAttachObjectARB          glAttachObjectARB_()
#define glLinkProgramARB           glLinkProgramARB_()
#define glUseProgramObjectARB      glUseProgramObjectARB_()
#define glValidateProgramARB       glValidateProgramARB_()
#define glUniform1fARB             glUniform1fARB_()
#define glUniform2fARB             glUniform2fARB_()
#define glUniform3fARB             glUniform3fARB_()
#define glUniform4fARB             glUniform4fARB_()
#define glUniform1iARB             glUniform1iARB_()
#define glUniform2iARB             glUniform2iARB_()
#define glUniform3iARB             glUniform3iARB_()
#define glUniform4iARB             glUniform4iARB_()
#define glUniform1fvARB            glUniform1fvARB_()
#define glUniform2fvARB            glUniform2fvARB_()
#define glUniform3fvARB            glUniform3fvARB_()
#define glUniform4fvARB            glUniform4fvARB_()
#define glUniform1ivARB            glUniform1ivARB_()
#define glUniform2ivARB            glUniform2ivARB_()
#define glUniform3ivARB            glUniform3ivARB_()
#define glUniform4ivARB            glUniform4ivARB_()
#define glUniformMatrix2fvARB      glUniformMatrix2fvARB_()
#define glUniformMatrix3fvARB      glUniformMatrix3fvARB_()
#define glUniformMatrix4fvARB      glUniformMatrix4fvARB_()
#define glGetObjectParameterfvARB  glGetObjectParameterfvARB_()
#define glGetObjectParameterivARB  glGetObjectParameterivARB_()
#define glGetInfoLogARB            glGetInfoLogARB_()
#define glGetAttachedObjectsARB    glGetAttachedObjectsARB_()
#define glGetUniformLocationARB    glGetUniformLocationARB_()
#define glGetActiveUniformARB      glGetActiveUniformARB_()
#define glGetUniformfvARB          glGetUniformfvARB_()
#define glGetUniformivARB          glGetUniformivARB_()
#define glGetShaderSourceARB       glGetShaderSourceARB_()
#pragma endregion

#pragma region GL_VERSION_3_0
GET_FUNCTION_POINTER(PFNGLCOLORMASKIPROC                          , glColorMaski                            )
GET_FUNCTION_POINTER(PFNGLGETBOOLEANI_VPROC                       , glGetBooleani_v                         )
GET_FUNCTION_POINTER(PFNGLGETINTEGERI_VPROC                       , glGetIntegeri_v                         )
GET_FUNCTION_POINTER(PFNGLENABLEIPROC                             , glEnablei                               )
GET_FUNCTION_POINTER(PFNGLDISABLEIPROC                            , glDisablei                              )
GET_FUNCTION_POINTER(PFNGLISENABLEDIPROC                          , glIsEnabledi                            )
GET_FUNCTION_POINTER(PFNGLBEGINTRANSFORMFEEDBACKPROC              , glBeginTransformFeedback                )
GET_FUNCTION_POINTER(PFNGLENDTRANSFORMFEEDBACKPROC                , glEndTransformFeedback                  )
GET_FUNCTION_POINTER(PFNGLBINDBUFFERRANGEPROC                     , glBindBufferRange                       )
GET_FUNCTION_POINTER(PFNGLBINDBUFFERBASEPROC                      , glBindBufferBase                        )
GET_FUNCTION_POINTER(PFNGLTRANSFORMFEEDBACKVARYINGSPROC           , glTransformFeedbackVaryings             )
GET_FUNCTION_POINTER(PFNGLGETTRANSFORMFEEDBACKVARYINGPROC         , glGetTransformFeedbackVarying           )
GET_FUNCTION_POINTER(PFNGLCLAMPCOLORPROC                          , glClampColor                            )
GET_FUNCTION_POINTER(PFNGLBEGINCONDITIONALRENDERPROC              , glBeginConditionalRender                )
GET_FUNCTION_POINTER(PFNGLENDCONDITIONALRENDERPROC                , glEndConditionalRender                  )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBIPOINTERPROC                , glVertexAttribIPointer                  )
GET_FUNCTION_POINTER(PFNGLGETVERTEXATTRIBIIVPROC                  , glGetVertexAttribIiv                    )
GET_FUNCTION_POINTER(PFNGLGETVERTEXATTRIBIUIVPROC                 , glGetVertexAttribIuiv                   )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI1IPROC                     , glVertexAttribI1i                       )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI2IPROC                     , glVertexAttribI2i                       )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI3IPROC                     , glVertexAttribI3i                       )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI4IPROC                     , glVertexAttribI4i                       )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI1UIPROC                    , glVertexAttribI1ui                      )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI2UIPROC                    , glVertexAttribI2ui                      )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI3UIPROC                    , glVertexAttribI3ui                      )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI4UIPROC                    , glVertexAttribI4ui                      )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI1IVPROC                    , glVertexAttribI1iv                      )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI2IVPROC                    , glVertexAttribI2iv                      )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI3IVPROC                    , glVertexAttribI3iv                      )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI4IVPROC                    , glVertexAttribI4iv                      )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI1UIVPROC                   , glVertexAttribI1uiv                     )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI2UIVPROC                   , glVertexAttribI2uiv                     )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI3UIVPROC                   , glVertexAttribI3uiv                     )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI4UIVPROC                   , glVertexAttribI4uiv                     )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI4BVPROC                    , glVertexAttribI4bv                      )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI4SVPROC                    , glVertexAttribI4sv                      )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI4UBVPROC                   , glVertexAttribI4ubv                     )
GET_FUNCTION_POINTER(PFNGLVERTEXATTRIBI4USVPROC                   , glVertexAttribI4usv                     )
GET_FUNCTION_POINTER(PFNGLGETUNIFORMUIVPROC                       , glGetUniformuiv                         )
GET_FUNCTION_POINTER(PFNGLBINDFRAGDATALOCATIONPROC                , glBindFragDataLocation                  )
GET_FUNCTION_POINTER(PFNGLGETFRAGDATALOCATIONPROC                 , glGetFragDataLocation                   )
GET_FUNCTION_POINTER(PFNGLUNIFORM1UIPROC                          , glUniform1ui                            )
GET_FUNCTION_POINTER(PFNGLUNIFORM2UIPROC                          , glUniform2ui                            )
GET_FUNCTION_POINTER(PFNGLUNIFORM3UIPROC                          , glUniform3ui                            )
GET_FUNCTION_POINTER(PFNGLUNIFORM4UIPROC                          , glUniform4ui                            )
GET_FUNCTION_POINTER(PFNGLUNIFORM1UIVPROC                         , glUniform1uiv                           )
GET_FUNCTION_POINTER(PFNGLUNIFORM2UIVPROC                         , glUniform2uiv                           )
GET_FUNCTION_POINTER(PFNGLUNIFORM3UIVPROC                         , glUniform3uiv                           )
GET_FUNCTION_POINTER(PFNGLUNIFORM4UIVPROC                         , glUniform4uiv                           )
GET_FUNCTION_POINTER(PFNGLTEXPARAMETERIIVPROC                     , glTexParameterIiv                       )
GET_FUNCTION_POINTER(PFNGLTEXPARAMETERIUIVPROC                    , glTexParameterIuiv                      )
GET_FUNCTION_POINTER(PFNGLGETTEXPARAMETERIIVPROC                  , glGetTexParameterIiv                    )
GET_FUNCTION_POINTER(PFNGLGETTEXPARAMETERIUIVPROC                 , glGetTexParameterIuiv                   )
GET_FUNCTION_POINTER(PFNGLCLEARBUFFERIVPROC                       , glClearBufferiv                         )
GET_FUNCTION_POINTER(PFNGLCLEARBUFFERUIVPROC                      , glClearBufferuiv                        )
GET_FUNCTION_POINTER(PFNGLCLEARBUFFERFVPROC                       , glClearBufferfv                         )
GET_FUNCTION_POINTER(PFNGLCLEARBUFFERFIPROC                       , glClearBufferfi                         )
GET_FUNCTION_POINTER(PFNGLGETSTRINGIPROC                          , glGetStringi                            )
GET_FUNCTION_POINTER(PFNGLISRENDERBUFFERPROC                      , glIsRenderbuffer                        )
GET_FUNCTION_POINTER(PFNGLBINDRENDERBUFFERPROC                    , glBindRenderbuffer                      )
GET_FUNCTION_POINTER(PFNGLDELETERENDERBUFFERSPROC                 , glDeleteRenderbuffers                   )
GET_FUNCTION_POINTER(PFNGLGENRENDERBUFFERSPROC                    , glGenRenderbuffers                      )
GET_FUNCTION_POINTER(PFNGLRENDERBUFFERSTORAGEPROC                 , glRenderbufferStorage                   )
GET_FUNCTION_POINTER(PFNGLGETRENDERBUFFERPARAMETERIVPROC          , glGetRenderbufferParameteriv            )
GET_FUNCTION_POINTER(PFNGLISFRAMEBUFFERPROC                       , glIsFramebuffer                         )
GET_FUNCTION_POINTER(PFNGLBINDFRAMEBUFFERPROC                     , glBindFramebuffer                       )
GET_FUNCTION_POINTER(PFNGLDELETEFRAMEBUFFERSPROC                  , glDeleteFramebuffers                    )
GET_FUNCTION_POINTER(PFNGLGENFRAMEBUFFERSPROC                     , glGenFramebuffers                       )
GET_FUNCTION_POINTER(PFNGLCHECKFRAMEBUFFERSTATUSPROC              , glCheckFramebufferStatus                )
GET_FUNCTION_POINTER(PFNGLFRAMEBUFFERTEXTURE1DPROC                , glFramebufferTexture1D                  )
GET_FUNCTION_POINTER(PFNGLFRAMEBUFFERTEXTURE2DPROC                , glFramebufferTexture2D                  )
GET_FUNCTION_POINTER(PFNGLFRAMEBUFFERTEXTURE3DPROC                , glFramebufferTexture3D                  )
GET_FUNCTION_POINTER(PFNGLFRAMEBUFFERRENDERBUFFERPROC             , glFramebufferRenderbuffer               )
GET_FUNCTION_POINTER(PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC , glGetFramebufferAttachmentParameteriv   )
GET_FUNCTION_POINTER(PFNGLGENERATEMIPMAPPROC                      , glGenerateMipmap                        )
GET_FUNCTION_POINTER(PFNGLBLITFRAMEBUFFERPROC                     , glBlitFramebuffer                       )
GET_FUNCTION_POINTER(PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC      , glRenderbufferStorageMultisample        )
GET_FUNCTION_POINTER(PFNGLFRAMEBUFFERTEXTURELAYERPROC             , glFramebufferTextureLayer               )
GET_FUNCTION_POINTER(PFNGLMAPBUFFERRANGEPROC                      , glMapBufferRange                        )
GET_FUNCTION_POINTER(PFNGLFLUSHMAPPEDBUFFERRANGEPROC              , glFlushMappedBufferRange                )
GET_FUNCTION_POINTER(PFNGLBINDVERTEXARRAYPROC                     , glBindVertexArray                       )
GET_FUNCTION_POINTER(PFNGLDELETEVERTEXARRAYSPROC                  , glDeleteVertexArrays                    )
GET_FUNCTION_POINTER(PFNGLGENVERTEXARRAYSPROC                     , glGenVertexArrays                       )
GET_FUNCTION_POINTER(PFNGLISVERTEXARRAYPROC                       , glIsVertexArray                         )

#define glColorMaski                            glColorMaski_()
#define glGetBooleani_v                         glGetBooleani_v_()
#define glGetIntegeri_v                         glGetIntegeri_v_()
#define glEnablei                               glEnablei_()
#define glDisablei                              glDisablei_()
#define glIsEnabledi                            glIsEnabledi_()
#define glBeginTransformFeedback                glBeginTransformFeedback_()
#define glEndTransformFeedback                  glEndTransformFeedback_()
#define glBindBufferRange                       glBindBufferRange_()
#define glBindBufferBase                        glBindBufferBase_()
#define glTransformFeedbackVaryings             glTransformFeedbackVaryings_()
#define glGetTransformFeedbackVarying           glGetTransformFeedbackVarying_()
#define glClampColor                            glClampColor_()
#define glBeginConditionalRender                glBeginConditionalRender_()
#define glEndConditionalRender                  glEndConditionalRender_()
#define glVertexAttribIPointer                  glVertexAttribIPointer_()
#define glGetVertexAttribIiv                    glGetVertexAttribIiv_()
#define glGetVertexAttribIuiv                   glGetVertexAttribIuiv_()
#define glVertexAttribI1i                       glVertexAttribI1i_()
#define glVertexAttribI2i                       glVertexAttribI2i_()
#define glVertexAttribI3i                       glVertexAttribI3i_()
#define glVertexAttribI4i                       glVertexAttribI4i_()
#define glVertexAttribI1ui                      glVertexAttribI1ui_()
#define glVertexAttribI2ui                      glVertexAttribI2ui_()
#define glVertexAttribI3ui                      glVertexAttribI3ui_()
#define glVertexAttribI4ui                      glVertexAttribI4ui_()
#define glVertexAttribI1iv                      glVertexAttribI1iv_()
#define glVertexAttribI2iv                      glVertexAttribI2iv_()
#define glVertexAttribI3iv                      glVertexAttribI3iv_()
#define glVertexAttribI4iv                      glVertexAttribI4iv_()
#define glVertexAttribI1uiv                     glVertexAttribI1uiv_()
#define glVertexAttribI2uiv                     glVertexAttribI2uiv_()
#define glVertexAttribI3uiv                     glVertexAttribI3uiv_()
#define glVertexAttribI4uiv                     glVertexAttribI4uiv_()
#define glVertexAttribI4bv                      glVertexAttribI4bv_()
#define glVertexAttribI4sv                      glVertexAttribI4sv_()
#define glVertexAttribI4ubv                     glVertexAttribI4ubv_()
#define glVertexAttribI4usv                     glVertexAttribI4usv_()
#define glGetUniformuiv                         glGetUniformuiv_()
#define glBindFragDataLocation                  glBindFragDataLocation_()
#define glGetFragDataLocation                   glGetFragDataLocation_()
#define glUniform1ui                            glUniform1ui_()
#define glUniform2ui                            glUniform2ui_()
#define glUniform3ui                            glUniform3ui_()
#define glUniform4ui                            glUniform4ui_()
#define glUniform1uiv                           glUniform1uiv_()
#define glUniform2uiv                           glUniform2uiv_()
#define glUniform3uiv                           glUniform3uiv_()
#define glUniform4uiv                           glUniform4uiv_()
#define glTexParameterIiv                       glTexParameterIiv_()
#define glTexParameterIuiv                      glTexParameterIuiv_()
#define glGetTexParameterIiv                    glGetTexParameterIiv_()
#define glGetTexParameterIuiv                   glGetTexParameterIuiv_()
#define glClearBufferiv                         glClearBufferiv_()
#define glClearBufferuiv                        glClearBufferuiv_()
#define glClearBufferfv                         glClearBufferfv_()
#define glClearBufferfi                         glClearBufferfi_()
#define glGetStringi                            glGetStringi_()
#define glIsRenderbuffer                        glIsRenderbuffer_()
#define glBindRenderbuffer                      glBindRenderbuffer_()
#define glDeleteRenderbuffers                   glDeleteRenderbuffers_()
#define glGenRenderbuffers                      glGenRenderbuffers_()
#define glRenderbufferStorage                   glRenderbufferStorage_()
#define glGetRenderbufferParameteriv            glGetRenderbufferParameteriv_()
#define glIsFramebuffer                         glIsFramebuffer_()
#define glBindFramebuffer                       glBindFramebuffer_()
#define glDeleteFramebuffers                    glDeleteFramebuffers_()
#define glGenFramebuffers                       glGenFramebuffers_()
#define glCheckFramebufferStatus                glCheckFramebufferStatus_()
#define glFramebufferTexture1D                  glFramebufferTexture1D_()
#define glFramebufferTexture2D                  glFramebufferTexture2D_()
#define glFramebufferTexture3D                  glFramebufferTexture3D_()
#define glFramebufferRenderbuffer               glFramebufferRenderbuffer_()
#define glGetFramebufferAttachmentParameteriv   glGetFramebufferAttachmentParameteriv_()
#define glGenerateMipmap                        glGenerateMipmap_()
#define glBlitFramebuffer                       glBlitFramebuffer_()
#define glRenderbufferStorageMultisample        glRenderbufferStorageMultisample_()
#define glFramebufferTextureLayer               glFramebufferTextureLayer_()
#define glMapBufferRange                        glMapBufferRange_()
#define glFlushMappedBufferRange                glFlushMappedBufferRange_()
#define glBindVertexArray                       glBindVertexArray_()
#define glDeleteVertexArrays                    glDeleteVertexArrays_()
#define glGenVertexArrays                       glGenVertexArrays_()
#define glIsVertexArray                         glIsVertexArray_()
#pragma endregion

#pragma region GL_VERSION_4_0
GET_FUNCTION_POINTER(PFNGLMINSAMPLESHADINGPROC,                glMinSampleShading                )
GET_FUNCTION_POINTER(PFNGLBLENDEQUATIONIPROC,                  glBlendEquationi                  )
GET_FUNCTION_POINTER(PFNGLBLENDEQUATIONSEPARATEIPROC,          glBlendEquationSeparatei          )
GET_FUNCTION_POINTER(PFNGLBLENDFUNCIPROC,                      glBlendFunci                      )
GET_FUNCTION_POINTER(PFNGLBLENDFUNCSEPARATEIPROC,              glBlendFuncSeparatei              )
GET_FUNCTION_POINTER(PFNGLDRAWARRAYSINDIRECTPROC,              glDrawArraysIndirect              )
GET_FUNCTION_POINTER(PFNGLDRAWELEMENTSINDIRECTPROC,            glDrawElementsIndirect            )
GET_FUNCTION_POINTER(PFNGLUNIFORM1DPROC,                       glUniform1d                       )
GET_FUNCTION_POINTER(PFNGLUNIFORM2DPROC,                       glUniform2d                       )
GET_FUNCTION_POINTER(PFNGLUNIFORM3DPROC,                       glUniform3d                       )
GET_FUNCTION_POINTER(PFNGLUNIFORM4DPROC,                       glUniform4d                       )
GET_FUNCTION_POINTER(PFNGLUNIFORM1DVPROC,                      glUniform1dv                      )
GET_FUNCTION_POINTER(PFNGLUNIFORM2DVPROC,                      glUniform2dv                      )
GET_FUNCTION_POINTER(PFNGLUNIFORM3DVPROC,                      glUniform3dv                      )
GET_FUNCTION_POINTER(PFNGLUNIFORM4DVPROC,                      glUniform4dv                      )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX2DVPROC,                glUniformMatrix2dv                )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX3DVPROC,                glUniformMatrix3dv                )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX4DVPROC,                glUniformMatrix4dv                )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX2X3DVPROC,              glUniformMatrix2x3dv              )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX2X4DVPROC,              glUniformMatrix2x4dv              )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX3X2DVPROC,              glUniformMatrix3x2dv              )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX3X4DVPROC,              glUniformMatrix3x4dv              )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX4X2DVPROC,              glUniformMatrix4x2dv              )
GET_FUNCTION_POINTER(PFNGLUNIFORMMATRIX4X3DVPROC,              glUniformMatrix4x3dv              )
GET_FUNCTION_POINTER(PFNGLGETUNIFORMDVPROC,                    glGetUniformdv                    )
GET_FUNCTION_POINTER(PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC,    glGetSubroutineUniformLocation    )
GET_FUNCTION_POINTER(PFNGLGETSUBROUTINEINDEXPROC,              glGetSubroutineIndex              )
GET_FUNCTION_POINTER(PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC,    glGetActiveSubroutineUniformiv    )
GET_FUNCTION_POINTER(PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC,  glGetActiveSubroutineUniformName  )
GET_FUNCTION_POINTER(PFNGLGETACTIVESUBROUTINENAMEPROC,         glGetActiveSubroutineName         )
GET_FUNCTION_POINTER(PFNGLUNIFORMSUBROUTINESUIVPROC,           glUniformSubroutinesuiv           )
GET_FUNCTION_POINTER(PFNGLGETUNIFORMSUBROUTINEUIVPROC,         glGetUniformSubroutineuiv         )
GET_FUNCTION_POINTER(PFNGLGETPROGRAMSTAGEIVPROC,               glGetProgramStageiv               )
GET_FUNCTION_POINTER(PFNGLPATCHPARAMETERIPROC,                 glPatchParameteri                 )
GET_FUNCTION_POINTER(PFNGLPATCHPARAMETERFVPROC,                glPatchParameterfv                )
GET_FUNCTION_POINTER(PFNGLBINDTRANSFORMFEEDBACKPROC,           glBindTransformFeedback           )
GET_FUNCTION_POINTER(PFNGLDELETETRANSFORMFEEDBACKSPROC,        glDeleteTransformFeedbacks        )
GET_FUNCTION_POINTER(PFNGLGENTRANSFORMFEEDBACKSPROC,           glGenTransformFeedbacks           )
GET_FUNCTION_POINTER(PFNGLISTRANSFORMFEEDBACKPROC,             glIsTransformFeedback             )
GET_FUNCTION_POINTER(PFNGLPAUSETRANSFORMFEEDBACKPROC,          glPauseTransformFeedback          )
GET_FUNCTION_POINTER(PFNGLRESUMETRANSFORMFEEDBACKPROC,         glResumeTransformFeedback         )
GET_FUNCTION_POINTER(PFNGLDRAWTRANSFORMFEEDBACKPROC,           glDrawTransformFeedback           )
GET_FUNCTION_POINTER(PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC,     glDrawTransformFeedbackStream     )
GET_FUNCTION_POINTER(PFNGLBEGINQUERYINDEXEDPROC,               glBeginQueryIndexed               )
GET_FUNCTION_POINTER(PFNGLENDQUERYINDEXEDPROC,                 glEndQueryIndexed                 )
GET_FUNCTION_POINTER(PFNGLGETQUERYINDEXEDIVPROC,               glGetQueryIndexediv               )

#define glMinSampleShading                glMinSampleShading_()
#define glBlendEquationi                  glBlendEquationi_()
#define glBlendEquationSeparatei          glBlendEquationSeparatei_()
#define glBlendFunci                      glBlendFunci_()
#define glBlendFuncSeparatei              glBlendFuncSeparatei_()
#define glDrawArraysIndirect              glDrawArraysIndirect_()
#define glDrawElementsIndirect            glDrawElementsIndirect_()
#define glUniform1d                       glUniform1d_()
#define glUniform2d                       glUniform2d_()
#define glUniform3d                       glUniform3d_()
#define glUniform4d                       glUniform4d_()
#define glUniform1dv                      glUniform1dv_()
#define glUniform2dv                      glUniform2dv_()
#define glUniform3dv                      glUniform3dv_()
#define glUniform4dv                      glUniform4dv_()
#define glUniformMatrix2dv                glUniformMatrix2dv_()
#define glUniformMatrix3dv                glUniformMatrix3dv_()
#define glUniformMatrix4dv                glUniformMatrix4dv_()
#define glUniformMatrix2x3dv              glUniformMatrix2x3dv_()
#define glUniformMatrix2x4dv              glUniformMatrix2x4dv_()
#define glUniformMatrix3x2dv              glUniformMatrix3x2dv_()
#define glUniformMatrix3x4dv              glUniformMatrix3x4dv_()
#define glUniformMatrix4x2dv              glUniformMatrix4x2dv_()
#define glUniformMatrix4x3dv              glUniformMatrix4x3dv_()
#define glGetUniformdv                    glGetUniformdv_()
#define glGetSubroutineUniformLocation    glGetSubroutineUniformLocation_()
#define glGetSubroutineIndex              glGetSubroutineIndex_()
#define glGetActiveSubroutineUniformiv    glGetActiveSubroutineUniformiv_()
#define glGetActiveSubroutineUniformName  glGetActiveSubroutineUniformName_()
#define glGetActiveSubroutineName         glGetActiveSubroutineName_()
#define glUniformSubroutinesuiv           glUniformSubroutinesuiv_()
#define glGetUniformSubroutineuiv         glGetUniformSubroutineuiv_()
#define glGetProgramStageiv               glGetProgramStageiv_()
#define glPatchParameteri                 glPatchParameteri_()
#define glPatchParameterfv                glPatchParameterfv_()
#define glBindTransformFeedback           glBindTransformFeedback_()
#define glDeleteTransformFeedbacks        glDeleteTransformFeedbacks_()
#define glGenTransformFeedbacks           glGenTransformFeedbacks_()
#define glIsTransformFeedback             glIsTransformFeedback_()
#define glPauseTransformFeedback          glPauseTransformFeedback_()
#define glResumeTransformFeedback         glResumeTransformFeedback_()
#define glDrawTransformFeedback           glDrawTransformFeedback_()
#define glDrawTransformFeedbackStream     glDrawTransformFeedbackStream_()
#define glBeginQueryIndexed               glBeginQueryIndexed_()
#define glEndQueryIndexed                 glEndQueryIndexed_()
#define glGetQueryIndexediv               glGetQueryIndexediv_()

#pragma pack (pop)
#endif// __OPENGL_EXT_H__